spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/audit}
spring.datasource.username=${DB_USERNAME:audit}
spring.datasource.password=${DB_PASSWORD:audit}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
